### ISSUE TITLE
I stuck in "make"

### ISSUE THREAD

**Issue by zhaoxuyan** [nicholaslocascio/ljpeg-ddsm#3]
cc  -O3  jpeg.o codec.o huffman.o io.o chendct.o leedct.o lexer.o marker.o stream.o transform.o -lm -o jpeg
lexer.o: file not recognized: 不可识别的文件格式
collect2: error: ld returned 1 exit status
makefile:30: recipe for target 'jpeg' failed
make: *** [jpeg] Error 1

**Comment by yib0liu** [comment]
I got similar error. Try the command "make clean" before "make".

**Comment by zhaoxuyan** [comment]
> I got similar error. Try the command "make clean" before "make".

Thanks. I have fixed it
